version: "3.8"

services:
  client:
    image: ghcr.io/gigio42/pisegundosem/client:latest
    ports:
      - "5500:8080"
    networks:
      - app-network
    restart: unless-stopped

  server:
    image: ghcr.io/gigio42/pisegundosem/server:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.docker
    command: >
      sh -c "dockerize -wait tcp://db:5432 -timeout 20s &&
      npx prisma migrate deploy &&
      node Server/server.js"
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: ghcr.io/gigio42/pisegundosem/database:latest
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - estoque-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  estoque-data:

networks:
  app-network: