version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: client.dockerfile
    image: ghcr.io/gigio42/pisegundosem/client:latest
    ports:
      - "5500:8080"
    networks:
      - app-network
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: server.dockerfile
    image: ghcr.io/gigio42/pisegundosem/server:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_POSTGRE_URL: ${DATABASE_POSTGRE_URL}
      HOST: 0.0.0.0
    command: >
      sh -c "npx prisma migrate deploy && node Server/server.js"
    networks:
      - app-network
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: database.dockerfile
    image: ghcr.io/gigio42/pisegundosem/database:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - estoque-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  estoque-data:

networks:
  app-network:
