version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: client.dockerfile
    ports:
      - "80:80"

  server:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_POSTGRE_URL: ${DATABASE_POSTGRE_URL}
      HOST: ${HOST}
    command: >
      sh -c "npx prisma db push && node Server/server.js"

  db:
    build:
      context: .
      dockerfile: database.dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
