name: Code formatting and linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install Dependencies
        run: npm install
      - name: Format Files
        run: npx prettier --config .prettierrc --write '**/*.js' '**/*.cjs' 'Client/**/*.html'
      - name: Run ESLint
        run: npx eslint '**/*.js' '**/*.cjs'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Marvin: formatando arquivos"
          commit_user_name: "Marvin"
          commit_user_email: "marvin@bot.noreply"