name: Run server and test

on: 
  push:
    branches:
      - main
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      HOST: localhost
      DATABASE_URL: "file:../Server/estoque.sqlite"

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'

    - name: Install dependencies
      run: npm i

    - name: Set script permissions
      run: chmod +x ./Test/generators/gerar_chapas.cjs
    
    - name: Start server and run tests
      run: npm run start-and-test

    - name: Show SQLite database
      run: |
        sudo apt-get install -y sqlite3
        echo -e ".headers on\n.mode column\nSELECT * FROM Chapas;" | sqlite3 Server/estoque.sqlite

    - name: Setup commit
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch origin main
        git checkout main
        git merge --strategy-option ours
        git add Server/estoque.sqlite
        git commit -m "Update estoque.sqlite with new Chapas" -a
        git push