name: Run server and test

on: 
  push:
    branches:
      - main
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'

    - name: Install dependencies
      run: npm i

    - name: Start server
      run: npx nodemon Server/server.js &
      env:
        PORT: 3000
        HOST: localhost
        DATABASE_URL: "sqlite:../Server/estoque.sqlite"
    - name: Run test
      run: node ./Test/generators/gerar_chapas.cjs

    - name: Reset database
      run: node ./Test/resetar_banco_de_dados.cjs

    - name: Seed database
      run: node ./Test/seed.cjs

    - name: Show SQLite database
      run: |
        sudo apt-get install -y sqlite3
        sqlite3 Server/estoque.sqlite .dump